// <auto-generated />
namespace _3aqarak.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_new_field_in_VillasAvailable_Collect_Price_Over_together : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_new_field_in_VillasAvailable_Collect_Price_Over_together));
        
        string IMigrationMetadata.Id
        {
            get { return "201911132029221_Add_new_field_in_VillasAvailable_Collect_Price_Over_together"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
