// <auto-generated />
namespace _3aqarak.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removephonevalidationfromclltables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removephonevalidationfromclltables));
        
        string IMigrationMetadata.Id
        {
            get { return "202003251853516_ remove phone validation from cll tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
